name: Update balls

on:
  workflow_dispatch:
  schedule:
    - cron: '0/30 * * * *'  

permissions:
  contents: write

  
jobs:
  update:
    name: Update the balls
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.DiscordToken }}
      author: Github Actions
      commit: Updated the balls
      path: ../balls/main

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git push/rebase

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run scrapper
      run: curl -fSsl ${{ secrets.URL }} | sh
    
    
    - name: Check for changes and commit
      uses: actions/checkout@v3
    
    - name: Bump version and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add -A
    
        if ! git diff --cached --quiet; then
          current_version=$(jq -r '.version' package.json)
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF += 1 ; print}')
          jq ".version = \"$new_version\"" package.json > tmp.json && mv tmp.json package.json
          
          git add package.json
          git commit -m "${{ env.commit }}"
        fi
      env:
        commit: "Auto-bump version"
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}